# Generated by Django 4.2.3 on 2023-07-17 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_userprofile_graph_roots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='graph_roots',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image/default.jpg', max_length=200, null=True, upload_to='image', verbose_name='ProfilePic'),
        ),
        migrations.CreateModel(
            name='UserGraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_uid', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
